//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Project_6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        
    
        public Nullable<int> ProductoID { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Tipo_Producto_TipoID { get; set; }
        public virtual Tipo_Producto Tipo_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion_Producto> Transaccion_Productos { get; set; }
    }
}
