//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Project_6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        
    
        public Nullable<int> TransaccionID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Cliente_PersonaID { get; set; }
        public virtual Cliente Cliente { get; set; }
        public Nullable<int> Empleado_PersonaID { get; set; }
        public virtual Empleado Empleado { get; set; }
        public Nullable<int> Estado_Transaccion_EstadoID { get; set; }
        public virtual Estado_Transaccion Estado_Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion_Producto> Transaccion_Productos { get; set; }
    }
}
